#ifndef TEXTURE_H
#define TEXTURE_H

#include <string>
#include "GL\glew.h"

using namespace std;

class Texture
{
public:
	/**
	 * Creates a usable texture in the OpenGL pipeline
	 * @param filePathOfImage
	 *		File path to the image that will define the texture
	 */
	Texture(const char *filePathOfImage);

	~Texture();

	/**
	 * Disable the texture
	 */
	void UnbindTexture();

	/**
	 * Activate the texture
	 */
	void BindTexture(uint8_t textureUnit);

	/**
	 * Returns the textures associated ID generated by OpenGL
	 */
	GLuint GetTextureId();

private:
	GLuint textureID;
};

#endif //TEXTURE_H